"""Add status, request_id, user_agent to audit_logs

The original audit_logs model (Phase 1) covered the write path but was
missing three fields a real audit trail needs:

- status: SUCCESS/FAILED — without this, "was the login/transfer this row
  describes actually successful?" has to be inferred from the action
  string alone (e.g. "LOGIN_FAILED" vs "LOGIN_SUCCESS"), which breaks for
  actions that don't encode outcome in their name.
- request_id: correlates every audit row from a single HTTP request (or a
  background task triggered by one) using the *existing* correlation ID
  already generated by RequestIdMiddleware — this migration does not
  introduce a second ID system, just gives the existing one a column to
  land in.
- user_agent: alongside ip_address, for basic anomaly review (e.g. a
  login succeeding from a wildly different user agent than usual).

Revision ID: 0012_audit_log_fields
Revises: 0011_card_payment_check
Create Date: 2026-08-31

"""
import sqlalchemy as sa

from alembic import op

revision = "0012_audit_log_fields"
down_revision = "0011_card_payment_check"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("audit_logs", sa.Column("status", sa.String(length=16), nullable=True))
    op.add_column("audit_logs", sa.Column("request_id", sa.String(length=64), nullable=True))
    op.add_column("audit_logs", sa.Column("user_agent", sa.String(length=512), nullable=True))

    op.create_index("ix_audit_logs_status", "audit_logs", ["status"])
    op.create_index("ix_audit_logs_request_id", "audit_logs", ["request_id"])


def downgrade() -> None:
    op.drop_index("ix_audit_logs_request_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_status", table_name="audit_logs")
    op.drop_column("audit_logs", "user_agent")
    op.drop_column("audit_logs", "request_id")
    op.drop_column("audit_logs", "status")
